function [Fx, COPx, COPy, sampRate] = importData(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   [Fx, COPx, COPy, sampRate] = IMPORTFILE(FILENAME, RESFREQ) Reads data from text file FILENAME for
%   the default selection.
%
%   [Fx, COPx, COPy, sampRate] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [Fx, COPx, COPy, sampRate] = importfile('P00_C3_f_2.tsv', 1, 60026);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/12/04 15:19:26

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

fprintf('Importing data. This may take a while...\n')

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
Data = table;
Data.VarName1 = cell2mat(raw(:, 1));
Data.VarName2 = cell2mat(raw(:, 2));
Data.VarName3 = cell2mat(raw(:, 3));
Data.VarName4 = cell2mat(raw(:, 4));
Data.VarName5 = cell2mat(raw(:, 5));
Data.VarName6 = cell2mat(raw(:, 6));
Data.VarName7 = cell2mat(raw(:, 7));
Data.VarName8 = cell2mat(raw(:, 8));
Data.VarName9 = cell2mat(raw(:, 9));

totalTime = Data.VarName2(1);
sampRate = Data.VarName2(2);
Fx = Data.VarName1(27:end);
Fy = Data.VarName2(27:end);
COPx = Data.VarName7(27:end);
COPy = Data.VarName8(27:end);

%% Saves a copy of the raw data in a .mat file
vars.COPx = COPx; vars.COPy = COPy; vars.Fx = Fx; vars.Fy = Fy; vars.sampRate = sampRate;
save('vars');

%% Force Plate Position Data (This will be implemented later...)
% Upper right corner
posXposY_X = Data.VarName2(10);
posXposY_Y = Data.VarName2(11);
% Uper left corner
negXposY_X = Data.VarName2(13);
negXposY_Y = Data.VarName2(14);
% Lower left corner
negXnegY_X = Data.VarName2(16);
negXnegY_Y = Data.VarName2(17);
% Lower right corner
posXnegY_X = Data.VarName2(19);
posXnegY_Y = Data.VarName2(20);

% %% Resample the Force data and display it:
% fprintf('Resampling Force data...\n')
% reFx = Fx(1:sampRate/resFreq:length(Fx));
% reFy = Fy(1:sampRate/resFreq:length(Fy));
% figure, subplot(2,2,1), plot(reFx,reFy), hold on;
% fprintf('Press any key to continue... \n\n')
% pause()
